### ISSUE TITLE
 Featured Bots do not show when badged with featured

### ISSUE THREAD

**Issue by ghost** [theADAMJR/dbots-api#16]
subject is mmg ( Featured Bots do not show when badged with featured) @theADAMJR

**Comment by theADAMJR** [comment]
Have you tried `dbots add-badge <bot_id> FEATURED`?

**Comment by ghost** [comment]
of course i have

**Comment by ghost** [comment]
23 days later for that smh XD but yes its fine i moved away from your scripts as they are not complete
