### ISSUE TITLE
i get a error when i stat it 

### ISSUE THREAD

**Issue by Duui3111** [theADAMJR/DBots-API#2]
config.json:20:21 - error TS1005: ':' expected.
 "dashboardURL: "http://localhost:4200",
                       ~~~~

config.json:20:21 - error TS1328: Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal.
 "dashboardURL: "http://localhost:4200",
                       ~~~~

config.json:20:25 - error TS1005: ',' expected.
   "dashboardURL: "http://localhost:4200",

**Comment by theADAMJR** [comment]
`"dashboardURL: "http://localhost:4200"` should be `"dashboardURL": "http://localhost:4200"`

**Comment by Duui3111** [comment]
now i get this error `Error: ENOENT: no such file or directory, stat 'D:\dist\dashboard\index.html'`

**Comment by theADAMJR** [comment]
Please pull the latest commit -> `git pull origin stable`
